- name: Setup SSH
  run: |
    mkdir -p ~/.ssh
    printf "%s" "${{ secrets.SSH_KEY }}" > ~/.ssh/awskey
    chmod 600 ~/.ssh/awskey
    ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts

- name: Create folder on AWS
  run: |
    ssh -i ~/.ssh/awskey -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p ~/myproject"
